# Generated by Django 4.1.5 on 2023-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='ID1',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
