# Generated by Django 4.1.5 on 2023-01-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_userprofilemodel_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='ID1',
        ),
    ]
