# Generated by Django 4.1.5 on 2023-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_results_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TempInput', models.TextField(max_length=200)),
            ],
        ),
    ]
