# Generated by Django 4.1.5 on 2023-01-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_tempinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempinput',
            old_name='TempInput',
            new_name='temp_input',
        ),
    ]
