# Generated by Django 4.1.5 on 2023-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_remove_tempinput_id_tempinput_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinput',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
