# Generated by Django 4.1.5 on 2023-01-30 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_tempinputmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempInputModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_choice_input', models.TextField(max_length=300)),
                ('symptom_list2', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TempInput',
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='clean_input',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
