# -*- coding: utf-8 -*-
"""Copy of 01_Assignment_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tCvCaOh2Kdh3LXeKcoHS5BOg9vYYELd

# Assignment 01
##### Python Basics I

This tutorial was written by Terry Ruas (University of Göttingen). The references for external contributors for which this material was anyhow adapted/inspired are in the Acknowledgments section (end of the document).

## Task 01 – Hello World!
Write a simple program that asks the user to input a name and outputs a simple greeting, such as ‘Hi Name! Nice to meet you!’ and in the other line, ‘Welcome to the Programing Course!’. 

*Hint: Check out the input () and print() function in Python.*
"""

Name = input()
print("Hi",Name,"! Nice to meet you!","\n","Welcome to the Programing Course!")

"""## Task 02 – Reversed Words
Write a program that reads in a word provided by the user and prints the word in a reversed order. For example, if the input is hello, the output should be ‘olleh’. 

- Use a loop structure 
- Use just array indexes 

"""

Revers = input()
for letter in range(len(Revers)):
  print(Revers[len(Revers)-letter-1],end ="")

"""## Task 03 –  Fibonacci Numbers
Write a program that reads in an upper bound (number) provided by the user and prints the sequence of Fibonacci numbers that are less or equal to the number given by the user. Use a while-loop for this task. 

The Fibonacci sequence is defined as 
$ F_{n}=F_{n−1}+F_{n−2}$. Use $F_{0}=0$ and $F_{1} = 1$ as seed values.  

For example, if the user inputs 6, the output should be 0, 1, 1, 2, 3, 5. 




"""

cuting_point = int(input())
first = 0
second = 1
while True:
  if first <= cuting_point :
    print(first,end="")
  else:
    print(".",end="")
    break
  if second <=cuting_point:
    print(",",end="")
  first , second = second , first+second

"""## Task 04 – Selective Printing 

Write a program that reads in an upper bound (number) provided by the user and prints all integer numbers that are less or equal to the upper bound except the integer numbers that are divisible by 3. Use the continue statement. For example, if the user enters 6 as the upper bound, the output should be 0, 1, 2, 4, 5.  
"""

uper = int(input())
for i in range(uper):
  if not(i%3 == 0):
    print(i,end=",")

"""## Task 05 – Triangle Checking   

Write a Python program that asks the user to input the lengths of the sides in a triangle and outputs whether the triangle is equilateral, isosceles, or scalene. The program should also check for the Triangle inequality $(z < x + y)$,  and prompt the user for a valid input. 

- An equilateral triangle is a triangle in which all three sides are of equal length. 
- An isosceles triangle is a triangle with (at least) two sides of equal length. 
- A scalene triangle is a triangle in which all three sides have different lengths. 

For example, if the user inputs a=3, b=4, c=5, the triangle is scalene. 

"""

a = int(input())
b = int(input())
c = int(input())
ItIsTriangel = True
Triangel = [a,b,c]
for x in Triangel:
  if x >= (a+b+c - x):
    print("This is not a Triangel") 
    ItIsTriangel = False
if ItIsTriangel:
  if a == b and b ==c:
    print("An equilateral triangle ")
  elif a==b or b==c or c==a:
    print("An isosceles triangle ")
  else:
    print("A scalene triangle")

"""## Task 06 – Decimal to Octal Conversion 

Write a program that reads a non-negative integer number in the decimal representation provided by the user and prints the octal representation of the number. For example, if the user enters 167, the output should be 247.  

Write a more general program that reads in a non-negative number (potentially including decimal places) in the decimal representation provided by the user and prints the octal representation of the number. For example, if the user enters 25.11, the output should be 31.0702436560507534. 
"""

def float_to_octal(x, num_digits = 17):

    whole = int(x)
    fraction = (x - whole) * 8

    # Convert first digit
    digit = int(fraction)
    fraction = (fraction - digit) * 8
    digits = [str(digit)]

    # Convert remaining digits
    i = 1
    while fraction and i < num_digits:
        digit = int(fraction)
        fraction = (fraction - digit) * 8
        digits.append(str(digit))
        i += 1
        
    return float("{:o}.{}".format(whole, "".join(digits)))

print(float_to_octal(float(input())))

"""## Acknowledgements

Redmond, Hsu, Saini, Gupta, Ramsey, Kondrich, Capoor, Cohen, Borus, Kincaid, Malik, and many others. - Stanford CS41
"""

