# -*- coding: utf-8 -*-
"""Copy of 05_Assignment_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWcpKMdgmDrpdAjHGnDTdAqcgkukpam3

# Assignment 05
#### Python Basics V - Text Processing

This tutorial was written by Terry L. Ruas (University of Göttingen). The references for external contributors for which this material was anyhow adapted/inspired are in the Acknowledgments section (end of the document).

This notebook will cover the following tasks:

1. Text Pre-Processing
2. Simple Text Analysis

## Task 01 – Text Pre-Processing
A computational analysis of natural language text typically requires several pre-processing steps, such as excluding irrelevant text parts, separating the text into words, phrases, or sentences depending on the analysis use case, removing so-called stop words, i.e., words that contain little to no semantic meaning, and normalizing the texts, e.g., by removing punctuation and capitalization.

Use the *download_file()* function developed in the past assignments to download the plain text versions of Shakespeare’s play [Macbeth](https://ia802707.us.archive.org/1/items/macbeth02264gut/0ws3410.txt) and Bacon’s [New Atlantis](https://ia801309.us.archive.org/24/items/newatlantis02434gut/nwatl10.txt). If you choose not to implement assignment 4, task 6, download the files manually. We will also provide some txt files.

Inspect these real-world texts manually to get an idea of what needs to be done to clean and prepare
the texts for computational analysis. Implement the following functions to perform common pre-processing steps on the texts:
1. *get_speaker_text()* – returns only the text spoken by the characters in the plays and removes all other text in the files, such as:
    - Information about the file, acknowledgements, copyright notices etc.
    - Headings indicating the act and scene
    - Stage instructions
    - Character names
2. *normalize_text()*
    - converts all text to lower case
    - removes all punctuation from the texts
3. *remove_stopwords()* – eliminates all stop words that are part of the list of English stop words (we provide two lists of stopwords, try both and see how they perform)
4. *tokenize_text()* – splits the cleaned text into words

This program is a pre-req for the next one.
"""

from os import execlp
import urllib.request

def download_file(url, path):
  try:     
    if url[-4:] == ".txt":
      p = path + '.txt'
      urllib.request.urlretrieve(url, p)
    else: 
      raise NameError('URL name wrong name') 
  except:
    return "No text file found at given URL, download aborted!"

download_file('https://ia801309.us.archive.org/24/items/newatlantis02434gut/nwatl10.txt','NA')
download_file('https://ia802707.us.archive.org/1/items/macbeth02264gut/0ws3410.txt','Mac')

def get_speaker_text(text):
    if 'The New Atlantis' in text:
      textlist = text.split('The New Atlantis')
      text = textlist[-2]
      flag = 1
      new_text = str()
      for t in text:
        if t == '\"':
          flag = flag*(-1)
        elif flag < 0:
          new_text += t
          """
      text = new_text
      new_text = str()
      flag = -1
      for t in text:
        if t == '\\':
          flag = flag*(-1)
        elif flag < 0:
          new_text += t"""
    elif 'THE TRAGEDIE OF MACBETH' in text:
      textlist = text.split('THE TRAGEDIE OF MACBETH')
      text = textlist[-2] 
      flag = 1
      new_text = str()
      for t in text:
        if t == ':'or t == '.':
          flag = flag*(-1)
        elif flag < 0:
          new_text += t
    return new_text

import string
def normalize_text(text):
  text = text.lower()
  text = text.translate(str.maketrans('', '', string.punctuation))
  return text

from logging import ERROR
import copy
def IsStopwords(word):
  list_of_stop_words = []
  with open('eng_stop_words.txt') as f:
    Lines = f.readlines()
    for line in Lines:
      list_of_stop_words.append(line.strip())
  if word in list_of_stop_words:
    return True
  else:
    return False

def remove_stopwords(word_list):
  #word_list is a list of words 
  try:
    wlist = copy.deepcopy(word_list)

    for word in word_list:
      if IsStopwords(word) or word == '':
        wlist.remove(word)
    return wlist
  except:
    return ERROR

def tokenize_text(text):
  word_list = text.split(' ')
  while '' in word_list:
    word_list.remove('')
  return word_list
print(tokenize_text('parsa apspxap\ndcpcpd ccdcdc ccc     ccc c'))

"""## Task 02 – Classes
The [Baconian theory](https://en.wikipedia.org/wiki/Baconian_theory_of_Shakespeare_authorship) holds that Sir Francis Bacon is the author of Shakespeare’s plays. We want to perform a very simple stylistic analysis between Shakespeare’s play Macbeth and Bacon’s New Atlantis. We check for words that frequently occur in both documents to see whether there are characteristic words that co-occur in the texts, which might give some support to the theory.

Your Task:
1. Download and pre-process the texts as follows:  
  New Atlantis
    1. *get_speaker_text()*
    2. *normalize_text()*
    3. *remove_stopwords()*
    4. *tokenize_text()*   
  
 Macbeth
    1. *get_speaker_text()*
    2. *normalize_text()*
        1. *utils_ocr.correct_ocr_errors()* – we will provide a function to deal with OCR errors.
    3. *remove_stopwords()*
    4. *tokenize_text()*
2. For the pre-processed texts, compute the list of word co-occurrence frequencies, i.e. which words occur in both documents and how often. Use the format:  
[term , frequency_doc1 , frequency_doc2 , sum_of_frequencies]  
Sort the list according to the sum of the frequencies in descending order.
3. Use the csv library to store the ordered word co-occurrence frequency list in a CSV file. **You can zip the csv and upload it to GitHub.**
"""

import utils_ocr
def openAndRead(nameOfFile):
  f = open(nameOfFile, "rb")
  text = f.read().decode(errors='replace')
  textlist = text.split('\n')
  newText = str()
  for x in textlist:
    newText += x
  text = newText
  textlist = text.split('\r')
  newText = str()
  for x in textlist:
    newText += x
  text = newText
  textlist = text.split('\\')
  newText = str()
  for x in textlist:
    newText += x
  return str(text)
# TODO Read is false !!!!!!
Bac_txt = openAndRead('NA.txt')
Bac_txt = get_speaker_text(Bac_txt)
Bac_txt = normalize_text(Bac_txt)
Bac_txt = tokenize_text(Bac_txt)
Bac_txt = remove_stopwords(Bac_txt)
print(Bac_txt)
Shaks_txt = openAndRead('Mac.txt')
Shaks_txt = get_speaker_text(Shaks_txt)
Shaks_txt = normalize_text(Shaks_txt)
Shaks_txt = utils_ocr.correct_ocr_errors(Shaks_txt)
Shaks_txt = tokenize_text(Shaks_txt)
print(Shaks_txt)

def Couinting(listOne,listTwo):
  preProsList = []
  used_words = []
  for word in listOne:
    if word not in used_words:
      used_words.append(word)
      preProsList.append([word,listOne.count(word),listTwo.count(word),listOne.count(word)+listTwo.count(word)])
  for word in listTwo:
    if word not in used_words:
      used_words.append(word)
      preProsList.append([word,listOne.count(word),listTwo.count(word),listOne.count(word)+listTwo.count(word)])
  return preProsList

print(Couinting(Shaks_txt,Bac_txt))




# on tabeee !!!!! 
# read 
# check